#!/usr/bin/python
import re
import os, sys
import json
import beanstalkc

def main():
    pre_check_failed_msg = ''
    for line in sys.stdin.xreadlines():
        if len(line) > 1024:
            pre_check_failed_msg = 'commit message line max 1024!'
            break
        line_array = line.strip().split(' ')
        if len(line_array) != 3:
            pre_check_failed_msg = 'tree len(array) must be 3!'
            break
        if not (re.match('^[a-zA-Z0-9_\.\-]+$', line_array[0]) and re.match('^\w+$', line_array[1]) and re.match('^[\w|/]+$', line_array[2])):
            pre_check_failed_msg = 'illegal branch name!'
            break
    if pre_check_failed_msg != '':
        print pre_check_failed_msg
        return 1
    return 0

if __name__ == '__main__':
    sys.exit(main())
