#!/usr/bin/python
import os, sys
import json
import beanstalkc

def main():
    max_line_count = 100
    for line in sys.stdin.xreadlines():
        max_line_count = max_line_count - 1
        if max_line_count < 0:
            return 1
    return 0

if __name__ == '__main__':
    return main()
