#!/usr/bin/python
import re
import os, sys
import json
import beanstalkc

def main():
    max_line_count = 50
    for line in sys.stdin.xreadlines():
        if len(line) > 1024:
            return 1
        line_array = line.strip().split(' ')
        if len(line_array) != 3:
            return 1
        max_line_count = max_line_count - 1
        if max_line_count < 0:
            return 1
        if not (re.match('^\w+$', line_array[0]) and re.match('^\w+$', line_array[1]) and re.match('^[\w|/]+$', line_array[2])):
            return 1
    return 0

if __name__ == '__main__':
    sys.exit(main())
